language: node_js
node_js: stable



# Travis-CI Caching
cache:
    directories:
      - node_modules



# S: Build Lifecycle
install:
  - npm install

before_script:
  - npm install -g hexo-cli

script:
  - hexo clean & hexo generate

# E: Build LifeCycle
